version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - "3500:3500"
    networks:
      - caddy_network
      - default

networks:
  caddy_network:
    external: true # Hubungkan ke network yang sama dengan Caddy utama Anda (sesuaikan jika nama network berbeda)
