services:
  backend:
    build: .
    container_name: suryabaru_backend # (Opsional disesuaikan agar tidak konflik nama container)
    restart: always
    expose:
      - "3500"
    env_file:
      - .env
    volumes:
      # Simpan backup di folder project server (host), bukan volume Docker internal
      - ./backups:/app/backups
    networks:
      - caddy_network
      - default

networks:
  caddy_network:
    external: true

volumes:
  caddy_data:
  caddy_config:
